# Generated by Django 2.0.2 on 2019-07-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190709_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Подсказка')),
            ],
            options={
                'verbose_name': 'Подсказка на квест',
                'verbose_name_plural': 'Подсказки на квесты',
            },
        ),
        migrations.RemoveField(
            model_name='questanswer',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='teamquest',
            name='answer',
        ),
        migrations.AddField(
            model_name='quest',
            name='answer',
            field=models.CharField(default='1', max_length=255, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestAnswer',
        ),
        migrations.AddField(
            model_name='questhint',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.Quest', verbose_name='Квест'),
        ),
    ]
