# Generated by Django 2.0.2 on 2019-07-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190709_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamquest',
            unique_together={('team', 'quest')},
        ),
    ]
