# Generated by Django 2.0.2 on 2019-07-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190709_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamquest',
            name='hints',
            field=models.SmallIntegerField(default=0, verbose_name='Количество подсказок'),
        ),
    ]
