# Generated by Django 2.0.2 on 2019-07-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teamquest_hints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamquest',
            options={'verbose_name': 'Ответ команды', 'verbose_name_plural': 'Ответы команд'},
        ),
    ]
