# Generated by Django 2.0.2 on 2019-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190709_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamquest',
            name='done_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата сдачи'),
        ),
    ]
